import { Ubuntu } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-ubuntu',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased bg-slate-200`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
